class Country {
  final String code;
  final String name;
  final String emoji;
  final String currency;
  final String currencyIso;
  final String decathlonDomain;
  final String zaraPath;
  final String jdDomain;      // e.g. "jdsports.fr"
  final String amazonDomain;
  final String ikeaPath;
  final String sephoraDomain;

  const Country({
    required this.code,
    required this.name,
    required this.emoji,
    required this.currency,
    required this.currencyIso,
    required this.decathlonDomain,
    required this.zaraPath,
    required this.jdDomain,
    required this.amazonDomain,
    required this.ikeaPath,
    required this.sephoraDomain,
  });
}

const List<Country> kCountries = [
  Country(
    code: 'FR',
    name: 'France',
    emoji: '🇫🇷',
    currency: '€',
    currencyIso: 'EUR',
    decathlonDomain: 'decathlon.fr',
    zaraPath: 'fr/fr',
    jdDomain: 'jdsports.fr',
    amazonDomain: 'amazon.fr',
    ikeaPath: 'fr/fr',
    sephoraDomain: 'sephora.fr',
  ),
  Country(
    code: 'ES',
    name: 'Espagne',
    emoji: '🇪🇸',
    currency: '€',
    currencyIso: 'EUR',
    decathlonDomain: 'decathlon.es',
    zaraPath: 'es/es',
    jdDomain: 'jdsports.es',
    amazonDomain: 'amazon.es',
    ikeaPath: 'es/es',
    sephoraDomain: 'sephora.es',
  ),
  Country(
    code: 'DE',
    name: 'Allemagne',
    emoji: '🇩🇪',
    currency: '€',
    currencyIso: 'EUR',
    decathlonDomain: 'decathlon.de',
    zaraPath: 'de/de',
    jdDomain: 'jdsports.de',
    amazonDomain: 'amazon.de',
    ikeaPath: 'de/de',
    sephoraDomain: 'sephora.de',
  ),
  Country(
    code: 'IT',
    name: 'Italie',
    emoji: '🇮🇹',
    currency: '€',
    currencyIso: 'EUR',
    decathlonDomain: 'decathlon.it',
    zaraPath: 'it/it',
    jdDomain: 'jdsports.it',
    amazonDomain: 'amazon.it',
    ikeaPath: 'it/it',
    sephoraDomain: 'sephora.it',
  ),
  Country(
    code: 'BE',
    name: 'Belgique',
    emoji: '🇧🇪',
    currency: '€',
    currencyIso: 'EUR',
    decathlonDomain: 'decathlon.be',
    zaraPath: 'be/fr',
    jdDomain: 'jdsports.be',
    amazonDomain: 'amazon.com.be',
    ikeaPath: 'be/fr',
    sephoraDomain: 'sephora.fr',
  ),
  Country(
    code: 'PT',
    name: 'Portugal',
    emoji: '🇵🇹',
    currency: '€',
    currencyIso: 'EUR',
    decathlonDomain: 'decathlon.pt',
    zaraPath: 'pt/pt',
    jdDomain: 'jdsports.pt',
    amazonDomain: 'amazon.es',
    ikeaPath: 'pt/pt',
    sephoraDomain: 'sephora.pt',
  ),
  Country(
    code: 'NL',
    name: 'Pays-Bas',
    emoji: '🇳🇱',
    currency: '€',
    currencyIso: 'EUR',
    decathlonDomain: 'decathlon.nl',
    zaraPath: 'nl/en',
    jdDomain: 'jdsports.nl',
    amazonDomain: 'amazon.nl',
    ikeaPath: 'nl/nl',
    sephoraDomain: 'sephora.de',
  ),
  Country(
    code: 'PL',
    name: 'Pologne',
    emoji: '🇵🇱',
    currency: 'zł',
    currencyIso: 'PLN',
    decathlonDomain: 'decathlon.pl',
    zaraPath: 'pl/pl',
    jdDomain: 'jdsports.pl',
    amazonDomain: 'amazon.pl',
    ikeaPath: 'pl/pl',
    sephoraDomain: 'sephora.pl',
  ),
  Country(
    code: 'UK',
    name: 'Royaume-Uni',
    emoji: '🇬🇧',
    currency: '£',
    currencyIso: 'GBP',
    decathlonDomain: 'decathlon.co.uk',
    zaraPath: 'uk/en',
    jdDomain: 'jdsports.co.uk',
    amazonDomain: 'amazon.co.uk',
    ikeaPath: 'gb/en',
    sephoraDomain: 'sephora.co.uk',
  ),
  Country(
    code: 'RO',
    name: 'Roumanie',
    emoji: '🇷🇴',
    currency: 'lei',
    currencyIso: 'RON',
    decathlonDomain: 'decathlon.ro',
    zaraPath: 'ro/en',
    jdDomain: 'jdsports.ro',
    amazonDomain: 'amazon.de',
    ikeaPath: 'ro/ro',
    sephoraDomain: 'sephora.ro',
  ),
  Country(
    code: 'HU',
    name: 'Hongrie',
    emoji: '🇭🇺',
    currency: 'Ft',
    currencyIso: 'HUF',
    decathlonDomain: 'decathlon.hu',
    zaraPath: 'hu/en',
    jdDomain: 'jdsports.hu',
    amazonDomain: 'amazon.de',
    ikeaPath: 'hu/hu',
    sephoraDomain: 'sephora.de',
  ),
  Country(
    code: 'CZ',
    name: 'Rép. Tchèque',
    emoji: '🇨🇿',
    currency: 'Kč',
    currencyIso: 'CZK',
    decathlonDomain: 'decathlon.cz',
    zaraPath: 'cz/en',
    jdDomain: 'jdsports.cz',
    amazonDomain: 'amazon.de',
    ikeaPath: 'cz/cs',
    sephoraDomain: 'sephora.cz',
  ),
];
